#! /usr/bin/env python

import sys
import traceback

def fun():
  more_fun()

def more_fun():
  print('Goodbye, cruel world')
  try:
    x = 1/0 # cause division by zero
  except Exception as e:
   print(f'Caught {e!s}', file=sys.stderr)
   # traceback.print_exception(e)
   # print(traceback.format_exc())
   traceback.print_exc()

fun()
